version: '3.8'
services:
    api:
        build: .
        ports:
            - '5001:5001'
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/multi-ecom-next-nest?schema=public
        depends_on:
            - postgres
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: multi-ecom-next-nest
        ports:
            - '5432:5432'
